version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=studentdb
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student


  etl:
    build: .
    command: python run.py
    volumes:
      - .:/etl-postgres
    depends_on:
      - db
